#!/usr/bin/env node
/**
 * Setup helper script for OmniLead frontend
 * This script helps verify and set up the frontend environment
 */

const fs = require('fs');
const path = require('path');

function checkEnvFile() {
  const envPath = path.join(__dirname, '.env');
  return fs.existsSync(envPath);
}

function createEnvTemplate() {
  const envPath = path.join(__dirname, '.env');
  
  if (fs.existsSync(envPath)) {
    console.log('⚠️  .env file already exists. Skipping creation.');
    return false;
  }
  
  const template = `# OmniLead Frontend Environment Configuration
# Generated by setup.js

# API Base URL
REACT_APP_API_URL=http://localhost:8000
`;
  
  fs.writeFileSync(envPath, template);
  console.log('✅ Created .env file');
  console.log('📝 Update REACT_APP_API_URL if your backend runs on a different port');
  return true;
}

function checkDependencies() {
  const packageJsonPath = path.join(__dirname, 'package.json');
  const nodeModulesPath = path.join(__dirname, 'node_modules');
  
  if (!fs.existsSync(packageJsonPath)) {
    console.log('❌ package.json not found');
    return false;
  }
  
  if (!fs.existsSync(nodeModulesPath)) {
    console.log('⚠️  node_modules not found');
    console.log('   Run: npm install');
    return false;
  }
  
  console.log('✅ Dependencies directory exists');
  return true;
}

function checkRequiredPackages() {
  const packageJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8')
  );
  
  const required = [
    'react',
    'react-dom',
    'react-router-dom',
    'axios',
    '@reduxjs/toolkit',
    'react-redux'
  ];
  
  const missing = required.filter(pkg => {
    return !packageJson.dependencies[pkg] && !packageJson.devDependencies[pkg];
  });
  
  if (missing.length > 0) {
    console.log(`⚠️  Missing packages: ${missing.join(', ')}`);
    console.log('   Run: npm install');
    return false;
  }
  
  console.log('✅ All required packages are in package.json');
  return true;
}

function main() {
  console.log('🚀 OmniLead Frontend Setup\n');
  console.log('='.repeat(50));
  
  // Check .env file
  console.log('\n📋 Checking environment configuration...');
  if (!checkEnvFile()) {
    console.log('Creating .env file template...');
    createEnvTemplate();
  } else {
    console.log('✅ .env file exists');
  }
  
  // Check dependencies
  console.log('\n📦 Checking dependencies...');
  const depsOk = checkDependencies();
  const packagesOk = checkRequiredPackages();
  
  console.log('\n' + '='.repeat(50));
  console.log('\n📝 Next Steps:');
  
  if (!depsOk || !packagesOk) {
    console.log('1. Install dependencies: npm install');
  }
  
  console.log('2. Start development server: npm start');
  console.log('3. The app will open at http://localhost:3000');
  console.log('\n✅ Setup check complete!');
}

main();

