#!/usr/bin/env python
"""
Setup helper script for OmniLead backend
This script helps verify and set up the backend environment
"""
import os
import sys
import secrets
from pathlib import Path

def generate_secret_key():
    """Generate a secure secret key"""
    return secrets.token_urlsafe(32)

def check_env_file():
    """Check if .env file exists"""
    env_path = Path(__file__).parent / '.env'
    return env_path.exists()

def create_env_template():
    """Create a .env file template"""
    env_path = Path(__file__).parent / '.env'
    
    if env_path.exists():
        print("⚠️  .env file already exists. Skipping creation.")
        return False
    
    secret_key = generate_secret_key()
    
    template = f"""# OmniLead Backend Environment Configuration
# Generated by setup.py

# Database Configuration
DATABASE_URL={DATABASE_URL}

# JWT Configuration
SECRET_KEY={SECRET_KEY}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=30

# OpenAI Configuration (Optional - for AI features)
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4

# Redis Configuration (Optional)
REDIS_URL=redis://localhost:6379

# Environment Settings
ENVIRONMENT=development
DEBUG=true

# Webhook Secrets (Optional)
WHATSAPP_WEBHOOK_SECRET=
FACEBOOK_WEBHOOK_SECRET=
INSTAGRAM_WEBHOOK_SECRET=

# Notification Services (Optional)
FIREBASE_SERVER_KEY=
SENDGRID_API_KEY=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=

# AWS S3 Configuration (Optional)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=omnilead-attachments
"""
    
    with open(env_path, 'w') as f:
        f.write(template)
    
    print(f"✅ Created .env file with generated SECRET_KEY")
    print(f"📝 Please update DATABASE_URL and other settings as needed")
    return True

def check_dependencies():
    """Check if required dependencies are installed"""
    try:
        import fastapi
        import sqlalchemy
        import alembic
        import pydantic_settings
        print("✅ Core dependencies are installed")
        return True
    except ImportError as e:
        print(f"❌ Missing dependency: {e.name}")
        print("   Run: pip install -r requirements.txt")
        return False

def check_database_connection():
    """Check if database connection can be established"""
    try:
        from app.config import settings
        from sqlalchemy import create_engine, text
        
        engine = create_engine(settings.database_url)
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        print("✅ Database connection successful")
        return True
    except Exception as e:
        print(f"⚠️  Database connection failed: {e}")
        print("   Please check your DATABASE_URL in .env file")
        return False

def check_migrations():
    """Check if migrations are set up"""
    alembic_dir = Path(__file__).parent / 'alembic'
    versions_dir = alembic_dir / 'versions'
    
    if not alembic_dir.exists():
        print("❌ Alembic directory not found")
        return False
    
    if not versions_dir.exists():
        print("⚠️  No migrations found. Run: alembic revision --autogenerate -m 'Initial migration'")
        return False
    
    migration_files = list(versions_dir.glob('*.py'))
    if migration_files:
        print(f"✅ Found {len(migration_files)} migration file(s)")
        return True
    else:
        print("⚠️  No migration files found")
        return False

def main():
    """Main setup function"""
    print("🚀 OmniLead Backend Setup\n")
    print("=" * 50)
    
    # Check .env file
    print("\n📋 Checking environment configuration...")
    if not check_env_file():
        print("Creating .env file template...")
        create_env_template()
    else:
        print("✅ .env file exists")
    
    # Check dependencies
    print("\n📦 Checking dependencies...")
    deps_ok = check_dependencies()
    
    if not deps_ok:
        print("\n❌ Please install dependencies first:")
        print("   pip install -r requirements.txt")
        sys.exit(1)
    
    # Check database
    print("\n🗄️  Checking database...")
    db_ok = check_database_connection()
    
    # Check migrations
    print("\n🔄 Checking migrations...")
    migrations_ok = check_migrations()
    
    print("\n" + "=" * 50)
    print("\n📝 Next Steps:")
    
    if not db_ok:
        print("1. Update DATABASE_URL in .env file")
        print("2. Ensure PostgreSQL is running")
        print("3. Create database: CREATE DATABASE omnilead;")
    
    if not migrations_ok:
        print("1. Create initial migration: alembic revision --autogenerate -m 'Initial migration'")
        print("2. Review the migration file")
        print("3. Apply migration: alembic upgrade head")
    else:
        print("1. Apply migrations: alembic upgrade head")
    
    print("2. Start server: python -m uvicorn app.main:socket_app --reload")
    print("\n✅ Setup check complete!")

if __name__ == "__main__":
    main()

